app:
  baseUrl: https://bfhldevapigw.healthrx.co.in
  generatePath: /hiring/generateWebhook/JAVA
  fallbackSubmitUrl: https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA
  auth:
    useBearer: false

  candidate:
    name: Ayush Gulati
    regNo: 22BCE3208
    email: ayush.gulati2022@vitstudent.ac.in

logging:
  level:
    root: INFO
    com.example.employee_department: INFO
